### ISSUE TITLE
The bad parameters in targetp

### ISSUE THREAD

**Issue by NailouZhang** [guigolab/FA-nf#6]
the pipline show 
------------
Caused by:
  Process `targetP (1)` terminated with an error exit status (2)

Command executed:

  targetp -P -c  input.1 > out_targetp_input.1

Command exit status:
  2

Command output:
  (empty)

Command error:
  flag provided but not defined: -P
  Usage of targetp:
    -batch int
      	Number of sequences that the tool will run simultaneously. Decrease or increase size depending on your system memory. (default 100)
    -fasta string
      	Input file in fasta format.
    -format string
      	Output format. 'long' for generating the predictions with plots, 'short' for the predictions without plots. (default "short")
    -gff3
      	Make gff3 file of processed sequences.
    -mature
      	Make fasta file with mature sequence.
    -org string
      	Organism. Non-plant: 'non-pl', Plant: 'pl'  (default "non-pl")
    -plot string
      	Plots output format. When long output selected, choose between 'png', 'eps' or 'none' to get just a tabular file. (default "png")
    -prefix string
      	Output files prefix. (default "Input file prefix")
    -stdout
      	Write the prediction summary to the STDOUT.
    -tmp string
      	Specify temporary file directory. (default "System default tmpdir")
    -verbose
      	Verbose output. Specify '-verbose=false' to avoid printing. (default true)
    -version
      	Prints version.

In main.nf
----------
process 'targetP' {

    label 'sigtarp'

    input:
    file seq from seq_file2

    output:
    file("out_targetp_${seq}") into (targetP_result1, targetP_result2)

    """
    targetp -P -c  $seq > out_targetp_${seq}
    """

So, how can I solve it?
-------

**Comment by toniher** [comment]
Dear Nailou,

thanks for reporting! Can you point which targetP version are you using?

Thanks!

**Comment by NailouZhang** [comment]
Hi, Toniher
I uesed targetp-2.0.Linux.tar.gz

**Comment by toniher** [comment]
Hi Nailou,
pipeline is set up to work with targetP 1.1 version. More details here:
https://github.com/biocorecrg/sigtarp_docker/tree/4f9a243a8491cac24dae78496990b4fa1b0a8b7b

We will try to provide a new pipeline release with updated software versions in the upcoming weeks.
Hope it helps!

**Comment by NailouZhang** [comment]
Thank you very much. I'm sorry that I made a mistake here and did not check the version of this package.

**Comment by lyn320** [comment]
hi,
I ran the local version of targetp-2.0.Linux.tar.gz (Default parameters) and the slurm files report:
 # TargetP-2.0	Organism: Non-Plant	Timestamp: 20220309220806
# ID	Prediction	noTP	SP	mTP	CS Position
TRINITY_DN100003_c0_g1_i1.p3	noTP	0.958083	0.001913	0.040004	
TRINITY_DN100008_c0_g1_i1.p1	noTP	0.605158	0.013404	0.381438	
TRINITY_DN100089_c0_g1_i1.p1	noTP	0.999502	0.000194	0.000304
im confused about the 'noTP',can you tell me what does that mean and what can be my  Filter criteria(SP or SP plus noTP) if im looking for sequence targeting extracellular.
thank you so much!

**Comment by toniher** [comment]
Hi,
your question is unrelated to this issue (that is already closed). On the other hand, that is a TargetP-specific question, instead of a FA-nf. In any case, you can check about it in the article of the program: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6769257/

**Comment by lyn320** [comment]
> Hi, your question is unrelated to this issue (that is already closed). On the other hand, that is a TargetP-specific question, instead of a FA-nf. In any case, you can check about it in the article of the program: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6769257/

Oops... by the way, thank you so much  for this reply!
