### ISSUE TITLE
Fails on test samples

### ISSUE THREAD

**Issue by iaconogi** [guigolab/FA-nf#8]
Dear Toni and Jaques
I tried a quick and dirty approach and run your pipeline over your examples, not touching anything in the *.config files (apart from setting docker instead of singularity).

Launching `main.nf` [insane_linnaeus] - revision: 94a6725623

Functional annotation pipeline

General parameters
------------------
Protein sequence file            : /data/nextflow_pipeline/mops/FaNf/FA-nf/dataset/aMicUni.selected_proteins.fa.gz
GFF Structural Annotation file              : /data/nextflow_pipeline/mops/FaNf/FA-nf/dataset/aMicUni.selected_genes.gff.gz
Species name                  : M.unicolor
KEGG species                  : hsa, dme, cel, ath, sce, cho, eco, nme, hpy, rpr, bsu, lla, cac, mge, mtu, ctr, bbu, syn, bth, dra, aae, mja, ape, aly, cit, tcc, gmx, fve, csv, vvi, sly, osa
, olu, ota, mis, cme, gsl
SQLite FA database        : /data/nextflow_pipeline/mops/FaNf/FA-nf/results/aMicUni.db
CD-Search queries will be skipped.
SignalP and targetP queries will be skipped.
Debugging... only the first 5 chunks will be processed
Skipping email

[75/b25591] Submitted process > kofamscan (1)
[ed/0510e8] Submitted process > cleanGFF
[c4/e75d5e] Submitted process > cdSearchHit (1)
[c2/803d2a] Submitted process > cdSearchFeat (1)
[08/6ac598] Submitted process > signalP_dummy (1)
[5f/2bf128] Submitted process > targetP_dummy (1)
[af/ff68ac] Submitted process > diamondFormat
[75/b25591] NOTE: Process `kofamscan (1)` terminated with an error exit status (1) -- Execution is retried (1)
[eb/794ecc] Submitted process > ipscn (1)
[af/ff68ac] NOTE: Process `diamondFormat` terminated with an error exit status (1) -- Execution is retried (1)
[60/349d35] Re-submitted process > kofamscan (1)
[eb/794ecc] NOTE: Process `ipscn (1)` terminated with an error exit status (127) -- Execution is retried (1)
[f4/f05bce] Submitted process > statsGFF
[22/277eb2] Submitted process > initDB (1)
[60/349d35] NOTE: Process `kofamscan (1)` terminated with an error exit status (1) -- Execution is retried (2)
[48/2b803b] Re-submitted process > diamondFormat
[48/2b803b] NOTE: Process `diamondFormat` terminated with an error exit status (1) -- Execution is retried (2)
[72/e41485] Re-submitted process > ipscn (1)
[53/d1bd2c] Re-submitted process > kofamscan (1)
[72/e41485] NOTE: Process `ipscn (1)` terminated with an error exit status (127) -- Execution is retried (2)
[cd/7b0194] Re-submitted process > diamondFormat
[08/8c0882] Re-submitted process > ipscn (1)
Error executing process > 'kofamscan (1)'

Caused by:
  Process `kofamscan (1)` terminated with an error exit status (1)

Command executed:

  exec_annotation --cpu 8 -p /nfs/db/kegg/2021-05-02/profiles -k /nfs/db/kegg/2021-05-02/ko_list -o koala_input.1 input.1

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Error: KO list not exist: /nfs/db/kegg/2021-05-02/ko_list

Work dir:
  /data/nextflow_pipeline/mops/FaNf/FA-nf/work/53/d1bd2c17702dd35e134fb1307cb3ec

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

Something went wrong
Oops .. something went wrong
WARN: Killing pending tasks (2)

**This is one of the work folders above, the one of Diamond**

work/af/ff68ac442ba629a1afbd29c71f5191/.command.log
iacongi@PROD-WGS-FASTQ1:/data/nextflow_pipeline/mops/FaNf/FA-nf$ cat work/af/ff68ac442ba629a1afbd29c71f5191/.command.log 
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
diamond v0.9.30.131 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 16
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /nfs/db/ncbi/202204/blastdb/db/swissprot
Opening the database file... No such file or directory
 [0s]
Error: Error opening file /nfs/db/ncbi/202204/blastdb/db/swissprot

**Comment by toniher** [comment]
Hi @iaconogi, it looks you didn't prepare needed dataset files and their indexes first. Check 'Dataset resources' section in the main README.md file

**Comment by toniher** [comment]
I close this. Please comment if there were any issue.
